appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ob7l2Hzd/EWBXLR7ioutJCjEXAUpoBZpn/5NAfutNj3rcPX9bFvpjlnemDbZJYSRr3vfBQDiHYPl1BAyu/ZT2LKczGKfSJ8WZIEGUhe/cxrg8BaAfQ4iW6v5bcKT3Pw7i4mYBp3yYPymUdteXCt/d+1R+7S3252/7tRB/BKoOjTWgbkdRP9qgqdiDzhwyjA3548bUMbnBK9CHyS7N+s0gPe2G6aBngCuIXPvm28xxxYO4ZaWGrSJ1TDThoJnXvnk48yMdIQg30PPs2dcD4SP9mQA/OJKFwN7k9YSnmVRrsLVJVc0ruvZOs0DbBhEMTobmj7zCTODtHj+ZLeF6uWIC3IcrkZdZt/nndOHRoISByXHTrs9eTkyoAuOeaGRJ3TwPa4hb0n9T61OKm75q/TROsAJN5R6E4TJIuFp8a0mCe4XPg4FmD/lttIUeif5btFnuc8KLRmsBZj5Zievo9+AFYDMuLAtcfD7gJdBdguHLLbT7wtNGx+95vi9h6U1Tz3DkFsZvIFcHPWi0/v3FoKI60n+cW7oyMUG6nS27lm5xYBFhIVBkVWlpfkR2PP76fbxrp9YaH1jCqn7XxRCcbA0Z7zVTNbatNN1mW/7t6NYzPK5toqAWw6Ekhv7YikUr3d4wm+E3jgSWqyoVyK7fhiqmZq0YHeQ/AfBu7EqVmSU6e4=}
