travis:
  secure:
    BINSTAR_TOKEN: KVSonpOJukDniunGjEsmMQUFPGkTUKV93y4QO6QHrJ6z1QlHup0GmdFPAvP37HOCgF6PTU8RXCAu0+1UfdqG9b7pDD7VmrvQLtbdQxWf+KJXiOUvutcIH6yzgmHfOFh1ZiQ3fGzBc9txN4X75sBwHmP8PJ//Zw3wDYXgHQSgMZN+sOh2Ss4lAf3RICEy93beuDo/nbpTaqKlRyhZRBbbWjKhQnVjaOrxA4Zm8gIf1b6LWuhFjlFwFyaqgffaYkctsqk9u2MJUTG9bArbLuRGtY1Y/F/sdHf7sDOW/GxE1RYvHVVkxr24thQMAJYlrVDMJ+lUFRTYCxxb43MVvtZcuwC+eEy8ZAAZrlWLemp2J+oyLNFzJLMOgkqXR0+0UsErD78HkmuZkm0LVq9Iejtj/X4uCoWXTrrL0MfCr/pwt/afUQs1K7F67DZMuTGDAu7FkQlvvqJcKtVbW14UhtnKjNgrE/XwuLrFva6qxskAYzzzWQKLSNdNY+TZ729cSlzkfxHnHdwE9HDvHXR4Q+bbWBdXoGb9ttXeK6yabFaEJgyrWe20ISMsd7GH2EQbu422ODOnFN5oqmSZXi8In/s1hwNFvtpTCY+OWmRKTfB/Cmw5Wj/wpiIkVrkYTYQHNSw+O8vRy9gB7QirDM5y6amUwBMh53jNeRz1P2F4+eEj8eU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
